-- H2 2.2.224;

CREATE SEQUENCE if not exists "PUBLIC"."CUSTOMER_SEQ" START WITH 1 RESTART WITH 301 INCREMENT BY 50;

CREATE TABLE if not exists "PUBLIC"."CUSTOMER"(
    "ID" BIGINT NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    PRIMARY KEY("ID")
);

CREATE TABLE if not exists "PUBLIC"."USERS"(
    "USERNAME" VARCHAR_IGNORECASE(50) NOT NULL,
    "PASSWORD" VARCHAR_IGNORECASE(500) NOT NULL,
    "ENABLED" BOOLEAN NOT NULL,
    PRIMARY KEY("USERNAME")
);

CREATE TABLE if not exists "PUBLIC"."AUTHORITIES"(
    "USERNAME" VARCHAR_IGNORECASE(50) NOT NULL,
    "AUTHORITY" VARCHAR_IGNORECASE(50) NOT NULL,
    FOREIGN KEY("USERNAME") REFERENCES "PUBLIC"."USERS"("USERNAME") NOCHECK
);

CREATE UNIQUE NULLS DISTINCT INDEX if not exists "PUBLIC"."IX_AUTH_USERNAME" ON "PUBLIC"."AUTHORITIES"("USERNAME" NULLS FIRST, "AUTHORITY" NULLS FIRST);
